### ISSUE TITLE
Suffers from type hinting with null exception

### ISSUE THREAD

**Issue by progmars** [nathanntg/lite-lexer#1]
`Argument 2 passed to Addins\Parser\Sections_Ordered::parse() must be an instance of Addins\Parser\ParserBlock, null given, called in ...\vendor\nathanntg\lite-lexer\parser.i.php on line 159 and defined in ordered.i.php line 39`

The root cause is described here:
https://stackoverflow.com/questions/14584145/cannot-pass-null-argument-when-using-type-hinting

You cannot pass null if using type hinting.

**Comment by nathanntg** [comment]
Thanks, I will get a fix for that shortly.

**Comment by nathanntg** [comment]
Pull request #2 should address this problem. I need to do a bit more testing before I merge it in, but feel free to try that branch.

**Comment by progmars** [comment]
Thank you for the fast fix. Yes, it works fine now.
